services:
  meilisearch-local:
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_ENV=development
    volumes:
      - meili_data:/meili_data
    ports:
      - 7700:7700

volumes:
  meili_data: