services:
  timescaledb-master:
    platform: linux/amd64
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb-master
    # restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      # POSTGRES_DB: postgres
      POSTGRES_REPLICATION_USER: postgres
      POSTGRES_REPLICATION_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - master_data:/var/lib/postgresql/data
    command: >
      postgres
      -c wal_level=replica
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c hot_standby=on
      -c 'shared_preload_libraries=timescaledb,pg_stat_statements' -c 'pg_stat_statements.track=all'

  timescaledb-replica1:
    platform: linux/amd64
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb-replica1
    # restart: unless-stopped
    depends_on:
      - timescaledb-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      # POSTGRES_DB: postgres
      PRIMARY_HOST: timescaledb-master
      REPLICATION_USER: postgres
      REPLICATION_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - replica1_data:/var/lib/postgresql/data
    command: >
      bash -c "
      until pg_basebackup -h timescaledb-master -D /var/lib/postgresql/data -U replicator -Fp -Xs -P -R;
      do
        echo 'Waiting for primary...';
        sleep 2;
      done;
      postgres
      "

  timescaledb-replica2:
    platform: linux/amd64
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb-replica2
    # restart: unless-stopped
    depends_on:
      - timescaledb-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      # POSTGRES_DB: postgres
      PRIMARY_HOST: timescaledb-master
      REPLICATION_USER: postgres
      REPLICATION_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - replica2_data:/var/lib/postgresql/data
    command: >
      bash -c "
      until pg_basebackup -h timescaledb-master -D /var/lib/postgresql/data -U replicator -Fp -Xs -P -R;
      do
        echo 'Waiting for primary...';
        sleep 2;
      done;
      postgres
      "

volumes:
  master_data:
  replica1_data:
  replica2_data: