version: '3.3'

services:
  # redis:
  #   container_name: redis
  #   image: redis:4.0.11-alping
  #   environment:
  #     - REDIS_PASSWORD=mypassword
  #     - REDIS_REPLICATION_mode=master
  #   command:
  #     - "--requirepass=mypassword"
  redisinsight:
    container_name: redisinsight
    image: redis/redisinsight:latest
    volumes:
      - redisinsight:/data
    ports:
      - 5540:5540

volumes:
  redisinsight: