version: '3.2'

services:
  cache:
    container_name: redis_cache
    image: redis:6.2.7
    ports:
      - "6379:6379"
    hostname: redis
    volumes: 
      - cache:/data
    networks:
      - redis
    restart: always
  
  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - redis
    restart: always

networks:
  redis:
    driver: bridge

volumes:
  cache: