services:
  bitwarden:
    depends_on:
      - db
    env_file:
      - settings.env
    image: bitwarden/self-host:beta
    ports:
      - "80:8080"
    volumes:
      - ./bitwarden:/etc/bitwarden
    # restart: always
 
  db:
    environment:
      MARIADB_USER: "bitwarden"
      MARIADB_PASSWORD: "super_strong_password"
      MARIADB_DATABASE: "bitwarden_vault"
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    image: mariadb:10
    volumes:
      - ./data:/var/lib/mysql
    # restart: always