version: '3.2'

services:
  db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always
    
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
       - pgadmin:/var/lib/pgadmin  
    ports:
      - "5050:80"
    networks:
      - postgres

networks:
  postgres:
    external: false
    driver: bridge

volumes:
    postgres:
    pgadmin:
