services:
  dpaste:
    container_name: dpaste
    image: darrenofficial/dpaste:latest
    environment:
      DATABASE_URL: sqlite:////db/dpaste.sqlite
      PORT: 8888
    volumes:
      - ./db:/db
    ports:
      - 8888:8888
    # restart: unless-stopped