# localstack - 💻 A fully functional local AWS cloud stack. Develop and test your cloud & Serverless apps offline

# guistack: http://localhost:6060

# swagger: http://localhost:4566/_localstack/swagger

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      # - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  guistack:
    platform: linux/amd64
    container_name: "guistack"
    image: visualvincent/guistack:latest
    ports:
      - "6060:80"
    environment:
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
      - AWS_REGION=eu-central-1
      - AWS_DYNAMODB_ENDPOINT_URL=http://host.docker.internal:4566
      - AWS_S3_ENDPOINT_URL=http://host.docker.internal:4566
      - AWS_SNS_ENDPOINT_URL=http://host.docker.internal:4566
      - AWS_SQS_ENDPOINT_URL=http://host.docker.internal:4566
      - AWS_S3_FORCE_PATH_STYLE=true