version: "3.3"
services:
  graphhopper:
    ports:
      - 8989:8989
    image: israelhikingmap/graphhopper
    command: --url https://download.geofabrik.de/europe/andorra-latest.osm.pbf
      --host 0.0.0.0
    restart: unless-stopped