services:
  nats-local:
    container_name: nats-local
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222
    volumes:
      - ./jetstream-cluster/nats-local:/data
    command: 
      - "--name=nats-local"
      - "--cluster_name=nats-local"
      - "--cluster=nats://nats-local:6222"
      - "--routes=nats-route://nats-local:6222"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"
    networks:
      - nats-local-network

networks:
  nats-local-network:
    driver: bridge