services:
  nats1:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./jetstream-cluster/nats1:/data
    command:
      - "--name=nats1"
      - "--cluster_name=c1"
      - "--cluster=nats://nats1:6222"
      - "--routes=nats-route://nats1:6222,nats-route://nats2:6222,nats-route://nats3:6222"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"
    networks:
      - nats-server

  nats2:
    image: nats:latest
    ports:
      - "4223:4222"
      - "8223:8222"
    volumes:
      - ./jetstream-cluster/nats2:/data
    command:
      - "--name=nats2"
      - "--cluster_name=c1"
      - "--cluster=nats://nats2:6222"
      - "--routes=nats-route://nats1:6222,nats-route://nats2:6222,nats-route://nats3:6222"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"
    networks:
      - nats-server

  nats3:
    image: nats:latest
    ports:
      - "4224:4222"
      - "8224:8222"
    volumes:
      - ./jetstream-cluster/nats3:/data
    command:
      - "--name=nats3"
      - "--cluster_name=c1"
      - "--cluster=nats://nats3:6222"
      - "--routes=nats-route://nats1:6222,nats-route://nats2:6222,nats-route://nats3:6222"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"
    networks:
      - nats-server

  # NATS dashboard instance running on the same private network.
  nui:
    image: ghcr.io/nats-nui/nui:edge
    volumes:
      - ./db:/db
    ports:
      - "4040:31311" 
    depends_on:
      - nats1
    networks:
      - nats-server

volumes:
  nats1: {}
  nats2: {}
  nats3: {}

networks:
  nats-server:
    driver: bridge